# Fichero: dockerfiles/mongo-express-aks/Dockerfile
# Descripción: Simplemente reutiliza la imagen oficial de Mongo Express.

# Para esta aplicación, no necesitamos personalización.
# Simplemente declaramos que nuestra imagen se basará en la oficial.
# La configuración (como la conexión a la base de datos) se la pasaremos
# más adelante a través de Kubernetes.
FROM mongo-express:latest

